/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoutineBuilderRouteImport } from './routes/routine-builder'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as ProductsHandleRouteImport } from './routes/products.$handle'
import { Route as ConcernsHandleRouteImport } from './routes/concerns.$handle'
import { Route as CollectionsHandleRouteImport } from './routes/collections.$handle'
import { Route as BrandsHandleRouteImport } from './routes/brands.$handle'

const RoutineBuilderRoute = RoutineBuilderRouteImport.update({
  id: '/routine-builder',
  path: '/routine-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcernsHandleRoute = ConcernsHandleRouteImport.update({
  id: '/concerns/$handle',
  path: '/concerns/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsHandleRoute = CollectionsHandleRouteImport.update({
  id: '/collections/$handle',
  path: '/collections/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsHandleRoute = BrandsHandleRouteImport.update({
  id: '/brands/$handle',
  path: '/brands/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/offers': typeof OffersRoute
  '/routine-builder': typeof RoutineBuilderRoute
  '/brands/$handle': typeof BrandsHandleRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/concerns/$handle': typeof ConcernsHandleRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/brands/': typeof BrandsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/offers': typeof OffersRoute
  '/routine-builder': typeof RoutineBuilderRoute
  '/brands/$handle': typeof BrandsHandleRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/concerns/$handle': typeof ConcernsHandleRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/brands': typeof BrandsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/offers': typeof OffersRoute
  '/routine-builder': typeof RoutineBuilderRoute
  '/brands/$handle': typeof BrandsHandleRoute
  '/collections/$handle': typeof CollectionsHandleRoute
  '/concerns/$handle': typeof ConcernsHandleRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/brands/': typeof BrandsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/offers'
    | '/routine-builder'
    | '/brands/$handle'
    | '/collections/$handle'
    | '/concerns/$handle'
    | '/products/$handle'
    | '/brands/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/offers'
    | '/routine-builder'
    | '/brands/$handle'
    | '/collections/$handle'
    | '/concerns/$handle'
    | '/products/$handle'
    | '/brands'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/offers'
    | '/routine-builder'
    | '/brands/$handle'
    | '/collections/$handle'
    | '/concerns/$handle'
    | '/products/$handle'
    | '/brands/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  OffersRoute: typeof OffersRoute
  RoutineBuilderRoute: typeof RoutineBuilderRoute
  BrandsHandleRoute: typeof BrandsHandleRoute
  CollectionsHandleRoute: typeof CollectionsHandleRoute
  ConcernsHandleRoute: typeof ConcernsHandleRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/routine-builder': {
      id: '/routine-builder'
      path: '/routine-builder'
      fullPath: '/routine-builder'
      preLoaderRoute: typeof RoutineBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerns/$handle': {
      id: '/concerns/$handle'
      path: '/concerns/$handle'
      fullPath: '/concerns/$handle'
      preLoaderRoute: typeof ConcernsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$handle': {
      id: '/collections/$handle'
      path: '/collections/$handle'
      fullPath: '/collections/$handle'
      preLoaderRoute: typeof CollectionsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$handle': {
      id: '/brands/$handle'
      path: '/brands/$handle'
      fullPath: '/brands/$handle'
      preLoaderRoute: typeof BrandsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  OffersRoute: OffersRoute,
  RoutineBuilderRoute: RoutineBuilderRoute,
  BrandsHandleRoute: BrandsHandleRoute,
  CollectionsHandleRoute: CollectionsHandleRoute,
  ConcernsHandleRoute: ConcernsHandleRoute,
  ProductsHandleRoute: ProductsHandleRoute,
  BrandsIndexRoute: BrandsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
